spring:
  jackson:
    serialization:
      indent-output: true
  profiles:
    active: db

openstack:
  keystone:
    url: https://keystone.jalju.com
    username: admin
    password: Asdf1234!

  glance:
    url: https://glance.jalju.com
