server:
  protocol: ${SERVICE_PROTOCOL}
  domain: ${SERVICE_DOMAIN}
  port: ${SERVICE_PORT:8080}
spring:
  profiles:
    active: db, google, discord, mail
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_PASSWORD}
            redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Google
            scope: # 추후 변경 가능
              - email
              - profile
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/directory.readonly
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id
openstack:
    url: ${OPENSTACK_URL}
    sa_username: ${OPENSTACK_BFF_USERNAME}
    sa_password: ${OPENSTACK_BFF_PASSWORD}

super-admin:
  user-id: ${SUPER_ADMIN_USER_ID}
  phone-number: ${SUPER_ADMIN_PHONE_NUMBER}
  user-name: ${SUPER_ADMIN_USER_NAME}

keycloak:
  url: ${KEYCLOAK_URL}

keycloak-temp:
  base-url: ${KEYCLOAK_BASE_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  redirect-uri: ${KEYCLOAK_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

oauth:
  success:
    redirect-url: ${OAUTH_SUCCESS_REDIRECT_URL}
  failure:
    redirect-url: ${OAUTH_FAILURE_REDIRECT_URL}
  cookie:
    domain: ${OAUTH_COOKIE_DOMAIN}

apm:
    server-url: ${APM_SERVER_URL}
logging:
  level:
    reactor.netty.http.client: TRACE

quick-start:
  default-image-id: ${DEFAULT_IMAGE_ID_X86_64}
