server:
  protocol: ${SERVICE_PROTOCOL}
  domain: ${SERVICE_DOMAIN}
  port: ${SERVICE_PORT:8080}
spring:
  profiles:
    active: db, google, discord, mail
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
openstack:
  url: ${OPENSTACK_URL}
  keystone:
    username: ${OPENSTACK_USERNAME}
    password: ${OPENSTACK_PASSWORD}
    project: ${OPENSTACK_PROJECT}
keycloak:
  url: ${KEYCLOAK_URL}

keycloak-temp:
  base-url: ${KEYCLOAK_BASE_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  redirect-uri: ${KEYCLOAK_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

