keystone:
  base-url: ${KEYSTONE_BASE_URL}
  token-url: ${KEYSTONE_TOKEN_URL}

cinder:
  base-url: ${CINDER_BASE_URL}
  volumes-url: ${CINDER_VOLUMES_URL}
  volumes-detail-url: ${CINDER_VOLUMES_DETAIL_URL}
